#!/bin/zsh

declare -A params

if [[ "$1" == "-l" ]]; then
    shift
    shift
fi

if [[ "$1" == "get" ]]; then
    read line
    while [[ -n "$line" ]]; do
        key=${line%%=*}
        value=${line#*=}
	params[$key]=$value
        read line
    done
    
    if [[ "$params[protocol]" == "ssh" ]]; then
	echo "ssh already"
	exit
    fi

    if [[ -z "$params[host]" ]]; then
	echo "no host"
	exit
    fi

    read "convert?You are connecting using the $params[protocol] protocol.
Would you like to convert to ssh? [Y/n] " < /dev/tty > /dev/tty

    if [[ "$convert" == "Y" ]]; then
     	for remote in `git remote`; do
	    new_url=`git remote get-url "$remote" | \
		sed "s/^$params[protocol]:\/\/\([^/]*\)\//git@\1:\//"`
	    git remote set-url $remote $new_url
	done
	while true; do
	    read "?Converted!
Press Control-C and try your git command again." < /dev/tty > /dev/tty
	done
    fi

    exit
fi
