#!/bin/zsh

declare -A params

if [[ "$1" == "-l" ]]; then
    shift
    shift
fi

if [[ "$1" == "get" ]]; then
    read line
    while [[ -n "$line" ]]; do
        key=${line%%=*}
        value=${line#*=}
	params[$key]=$value
        read line
    done  
    
    if [[ "$params[protocol]" != "ssh" ]]; then
	exit
    fi

    if [[ -z "$params[host]" ]]; then
	exit
    fi

    read "convert?You are connecting using the $params[protocol] protocol.  Would you like to convert to ssh? [Y/n] "

    if [[ "$convert" == "Y" ]]; then
     	for k in "${(@k)params}"; do
	    echo "$k -> $assoc_array[$params]"
	done
    fi
    
#    echo username=$user
#    echo password=$pass
fi
