#!/bin/zsh

declare -A params

if [[ "$1" == "-l" ]]; then
    shift
    lpassuser=$1
    shift
fi

if [[ "$1" == "get" ]]; then
    read line
    while [[ -n "$line" ]]; do
        key=${line%%=*}
        value=${line#*=}
	params[$key]=$value
        read line
    done  
    
    if [[ "$params[protocol]" != "https" ]]; then
	exit
    fi

    if [[ -z "$params[host]" ]]; then
	exit
    fi
    
    lpass ls > /dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        if [[ -z "$lpassuser" ]]; then
            read "lpassuser?Lastpass username: " < /dev/tty > /dev/tty
        fi
        if [[ -z "$lpassuser" ]]; then
            exit
        fi
        lpass login $lpassuser < /dev/tty > /dev/tty
        if [[ $? -ne 0 ]]; then
            echo "Failed to login to lastpass" > /dev/stderr
            exit
        fi
    fi

    user=`lpass show --username $params[host]`
    pass=`lpass show --password $params[host]`

    if [[ -z "$user" ]] || [[ -z "$pass" ]]; then
        echo "Couldn't find host in lastpass DB." > /dev/stderr
        exit
    fi

    echo username=$user
    echo password=$pass
fi
